=== dombigreta/XMLAssignment/xml/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="books"
           xmlns="books"
           elementFormDefault="qualified">

    <xs:complexType name="book_type">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="description"  type="xs:string"/>
            <xs:element name="amount-available" type="xs:integer"/>
            <xs:element name="price" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="Id" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                <xs:pattern value="[0-9]{4}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" type="book_type" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dombigreta/XMLAssignment/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns="books"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="books  book.xsd ">
    <book Id="1234">
        <title>Maradj velem</title>
        <description>Lorem ipsum dolor sit amet, consectetur adipiscing elit</description>
        <amount-available>3</amount-available>
        <price>1200</price>
    </book>

    <book Id="2345">
        <title>Beépített hercegnő </title>
        <description>Lorem ipsum dolor sit amet, consectetur adipiscing elit</description>
        <amount-available>2</amount-available>
        <price>1000</price>
    </book>

    <book Id="3456">
        <title>Enyém a főszerep</title>
        <description>Lorem ipsum dolor sit amet, consectetur adipiscing elit</description>
        <amount-available>10</amount-available>
        <price>4300</price>
    </book>

    <book Id="4567">
        <title>Csók Párizsban</title>
        <description>Lorem ipsum dolor sit amet, consectetur adipiscing elit</description>
        <amount-available>7</amount-available>
        <price>500</price>
    </book>

    <book Id="5678">
        <title>Zűrzavar a vonal végén</title>
        <description>Lorem ipsum dolor sit amet, consectetur adipiscing elit</description>
        <amount-available>1</amount-available>
        <price>4500</price>
    </book>
</books>
